/**
 * Products the owner listed in the WhatsApp chat (the gitignored `chat/` export), read by
 * `scripts/import-chat-products.ts`. Names, prices and ratings are the owner's captions; a rating that only
 * appears on a label in his own photo is used when the caption is silent. Everything else is left empty for
 * staff to fill in on the dashboard.
 *
 * Two batches so far: the price list of 2 October 2026 (his own photos and videos), and the catalogue he sent
 * on the evening of 3 October (the makers' pictures, each with a pasted description). In the second batch one
 * picture often stands for several sizes of a model, and a pasted specification sometimes belongs to the item
 * before it: where the title and the specification disagree, the rating is left out and a note says so.
 * Descriptions are short and written here from the facts he gave, not his pasted text.
 *
 * To add more: append an entry, put its files in `chat/`, run `pnpm import:chat`, then `pnpm import:chat --apply`.
 */

export interface ChatMedia {
  /** File name inside `chat/`. A `.mp4` is uploaded as a video. */
  file: string;
  /** What it shows: the alt text of a photo, the caption of a video. */
  alt: string;
  /** Keep only this part of a photo, in pixels: [left, top, width, height]. Cuts away a screenshot's borders, a passer-by, or another shop's phone number. */
  crop?: [number, number, number, number];
}

export interface ChatProduct {
  name: string;
  /** Category slug. */
  category: string;
  brand: string | null;
  /** Whole naira, or null when the owner gave no price ("Price on request"). */
  priceNgn: number | null;
  /** Values for the category's spec fields. */
  specs?: Record<string, string | number>;
  /** One short paragraph for the product page. */
  description?: string;
  /** The same file may appear on several products when one picture stands for a whole range. */
  media: ChatMedia[];
  /** DRAFT (hidden) for items read off a label that the owner has not named or priced himself. Default: PUBLISHED. */
  status?: "DRAFT" | "PUBLISHED";
  /** Something a person should check; printed when the import runs. */
  note?: string;
}

/** More from the owner about a product that is already on the site. Nothing there is replaced. */
export interface ChatAddition {
  /** The product's web address, as first imported (a later rename is followed). */
  slug: string;
  /** Added after the product's own photos and videos, unless already there. */
  media: ChatMedia[];
  /** Used only while the product has no description. */
  description?: string;
}

/** Brand names as printed on the products. The first list of brands was typed from memory and had these two wrong. */
export const BRAND_RENAMES = [
  { fromSlug: "lvstupsun", name: "LVTOPSUN" },
  { fromSlug: "ecolione", name: "Ecolion" },
];

const HYBRID = "Hybrid";
const ALL_IN_ONE = "All-in-one";
const LFP = "LiFePO4";
const PURE_SINE = "Pure sine wave";
const LOW_FREQUENCY = "Low frequency (transformer based)";
const LOW_FREQUENCY_HYBRID = "Hybrid, low frequency (transformer based)";
const FREEZER_POWER = "DC 12V/24V or AC 220V";

// The owner pasted the same few sentences for every size of a range. These say it once, in our own words.
const felicityLight = (watts: number) =>
  `${watts}W all-in-one solar street light: the solar panel, LED lamp, lithium battery and controller are built into one unit, so it goes up without any wiring. Motion and light sensors bring it on at dusk and off at dawn. IP65 waterproof.`;
const yohakoLowFrequency = (batteries: string) =>
  `Pure sine wave, low-frequency inverter built on a transformer. It can start from the battery with no mains, and restarts by itself when mains power returns. Works with ${batteries} batteries.`;
const YOHAKO_HYBRID = yohakoLowFrequency("AGM deep-cycle, gel and lithium");
const YOHAKO_TOWER = yohakoLowFrequency("AGM deep-cycle and gel");
const YOHAKO_OLD_LITHIUM = "Lithium iron phosphate (LiFePO4) battery for solar systems, with aluminium-shell cells, a battery management system and an anti-static metal case.";
const YOHAKO_WIFI_LITHIUM = "LiFePO4 lithium battery with an LCD screen and Wi-Fi. Rated for over 6,000 cycles, with up to 90% of its capacity usable. IP21.";
const YOHAKO_SURFACE_PUMP = "Brushless centrifugal surface water pump that runs from solar panels (DC) or from mains (AC).";
const YOHAKO_MPPT = "MPPT solar charge controller with fast tracking (99.5% tracking efficiency) and up to 98.5% conversion efficiency.";
const YOHAKO_FREEZER = "Runs straight from a 12V or 24V DC supply such as a solar system, or from mains through an adaptor. Holds -18°C in 55°C heat. A+++ efficiency.";

export const CHAT_PRODUCTS: ChatProduct[] = [
  // ─── Inverters ─────────────────────────────────────────────────────────────
  {
    name: "Felicity 6kVA Hybrid Inverter 48V (IVEM6048-II)",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 550_000,
    specs: { ratedKva: 6, ratedContinuousW: 6000, systemVoltage: 48, type: HYBRID },
    media: [
      { file: "IMG-20261002-WA0005.jpg", alt: "Felicity 6kVA hybrid inverter in its carton" },
      { file: "IMG-20260921-WA0095.jpg", alt: "Rating label of the Felicity IVEM6048-II inverter: 6000VA / 6000W, 48V" },
    ],
  },
  {
    name: "Felicity 10kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 800_000,
    specs: { ratedKva: 10, systemVoltage: 48, type: HYBRID },
    media: [{ file: "IMG-20261002-WA0052.jpg", alt: "Felicity 10kVA hybrid inverter with its user guide" }],
  },
  {
    name: "Felicity IVGM 20kVA Three-Phase Inverter",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 3_400_000,
    specs: { ratedKva: 20, type: "Three-phase" },
    media: [{ file: "IMG-20261002-WA0033.jpg", alt: "Felicity IVGM 20kVA three-phase inverter unpacked with its accessory boxes" }],
  },
  {
    name: "Yohako 1.5kVA Pure Sine Wave Inverter 24V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: 250_000,
    specs: { ratedKva: 1.5, systemVoltage: 24, type: "Pure sine wave" },
    media: [{ file: "IMG-20261002-WA0032.jpg", alt: "Yohako 1.5kVA pure sine wave inverter beside its carton" }],
  },
  {
    name: "Deye 16kVA Inverter 48V",
    category: "inverters",
    brand: "Deye",
    priceNgn: 3_200_000,
    specs: { ratedKva: 16, systemVoltage: 48 },
    media: [{ file: "IMG-20261002-WA0045.jpg", alt: "Deye inverter, front view" }],
    note: "The owner's two Deye photos were swapped: the one he captioned 16kVA shows a wall sign reading SUN-20K, so it is on the 20kVA product and this one has the other photo.",
  },
  {
    name: "Deye 20kVA Three-Phase Hybrid Inverter",
    category: "inverters",
    brand: "Deye",
    priceNgn: 4_000_000,
    specs: { ratedKva: 20, type: "Three-phase hybrid" },
    media: [{ file: "IMG-20261002-WA0046.jpg", alt: "Deye SUN-20K three-phase hybrid inverter on a showroom wall" }],
  },
  {
    name: "Deye 30kVA Hybrid Inverter (High Voltage)",
    category: "inverters",
    brand: "Deye",
    priceNgn: 5_800_000,
    specs: { ratedKva: 30, type: "Hybrid, high voltage" },
    media: [{ file: "IMG-20261002-WA0047.jpg", alt: "Deye 30kVA high-voltage hybrid inverter, front view", crop: [0, 0, 720, 1262] }],
  },
  {
    name: "Deye 6kW Hybrid Inverter",
    category: "inverters",
    brand: "Deye",
    priceNgn: 550_000,
    specs: { type: HYBRID },
    media: [{ file: "IMG-20261002-WA0056.jpg", alt: "Deye 6kW hybrid inverter, front view", crop: [14, 159, 512, 641] }],
  },
  {
    name: "LVTOPSUN 4kW Hybrid Inverter",
    category: "inverters",
    brand: "LVTOPSUN",
    priceNgn: null,
    specs: { type: HYBRID },
    media: [{ file: "IMG-20261002-WA0057.jpg", alt: "LVTOPSUN LVTS-4KW-24V-HYD hybrid inverter" }],
    note: "No price given. The caption says 48V but the picture is the 24V model (LVTS-4KW-24V-HYD), so the voltage is left out of the name.",
  },
  {
    name: "LVTOPSUN 6kW Hybrid Inverter 48V",
    category: "inverters",
    brand: "LVTOPSUN",
    priceNgn: 500_000,
    specs: { ratedKva: 6, systemVoltage: 48, type: HYBRID },
    media: [{ file: "IMG-20261002-WA0059.jpg", alt: "LVTOPSUN LVTS-6KW-48V-HYD hybrid inverter" }],
  },
  {
    name: "LVTOPSUN 12kW Hybrid Inverter 48V",
    category: "inverters",
    brand: "LVTOPSUN",
    priceNgn: 1_000_000,
    specs: { ratedKva: 12, systemVoltage: 48, type: HYBRID },
    media: [{ file: "IMG-20261002-WA0060.jpg", alt: "LVTOPSUN LVTS-12KW-48V-HYD hybrid inverter" }],
  },
  {
    name: "LVTOPSUN 15kW Three-Phase Inverter",
    category: "inverters",
    brand: "LVTOPSUN",
    priceNgn: null,
    specs: { type: "Three-phase" },
    media: [{ file: "IMG-20261002-WA0036.jpg", alt: "LVTOPSUN 15kW three-phase inverter", crop: [0, 246, 678, 530] }],
    note: "No price given.",
  },

  // ─── Lithium batteries ─────────────────────────────────────────────────────
  {
    name: "Felicity TG2 10kWh Lithium Battery 51.2V",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 1_550_000,
    specs: { capacityKwh: 10, voltage: 51.2 },
    media: [{ file: "IMG-20261002-WA0006.jpg", alt: "Felicity TG2 10kWh lithium battery unpacked beside its crate" }],
  },
  {
    name: "Felicity TG2 15kWh Lithium Battery",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 2_000_000,
    specs: { capacityKwh: 15 },
    media: [{ file: "IMG-20261002-WA0007.jpg", alt: "Felicity TG2 15kWh standing lithium battery" }],
  },
  {
    name: "Felicity 15kWh Lithium Battery 48V (Old Model)",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 2_000_000,
    specs: { capacityKwh: 15, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0028.jpg", alt: "Front and back of the older Felicity 15kWh lithium battery", crop: [0, 100, 1080, 843] }],
  },
  {
    name: "Felicity FLA 5kWh Lithium Battery 24V",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 1_000_000,
    specs: { capacityKwh: 5, voltage: 24 },
    media: [{ file: "IMG-20261002-WA0014.jpg", alt: "Felicity FLA 5kWh 24V lithium battery with its display on" }],
  },
  {
    name: "Felicity FLA 5kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 1_050_000,
    specs: { capacityKwh: 5, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0015.jpg", alt: "Felicity FLA 5kWh 48V lithium battery in its carton" }],
  },
  {
    name: "Felicity 5kWh Lithium Battery 48V (Old Model)",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 1_000_000,
    specs: { capacityKwh: 5, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0054.jpg", alt: "Older Felicity 5kWh 48V lithium battery, front view", crop: [0, 96, 768, 984] }],
  },
  {
    name: "Felicity FLA TG2 17.5kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 2_100_000,
    specs: { capacityKwh: 17.5, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0027.jpg", alt: "Felicity FLA TG2 17.5kWh lithium battery in its crate" }],
  },
  {
    name: "Felicity 17.5kWh Standing Lithium Battery",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 2_400_000,
    specs: { capacityKwh: 17.5 },
    media: [{ file: "VID-20261002-WA0062.mp4", alt: "Video of the Felicity 17.5kWh standing lithium battery and its rating label" }],
  },
  {
    name: "Felicity 25kWh Lithium Battery",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 4_000_000,
    specs: { capacityKwh: 25 },
    media: [{ file: "IMG-20261002-WA0053.jpg", alt: "Felicity 25kWh lithium battery on wheels" }],
  },
  {
    name: "Felicity HOPE1000 1kWh Lithium Battery",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: null,
    specs: { capacityKwh: 1, cells: "LiFePO4" },
    media: [
      { file: "IMG-20260921-WA0094.jpg", alt: "Felicity HOPE1000 standing on its carton" },
      { file: "IMG-20260921-WA0092.jpg", alt: "Rating label of the Felicity HOPE1000: 1kWh LiFePO4 battery, 250W", crop: [25, 0, 805, 1056] },
    ],
    note: "No price given.",
  },
  {
    name: "Pattern 15kWh LiFePO4 Lithium Battery",
    category: "lithium-batteries",
    brand: "Pattern",
    priceNgn: 1_700_000,
    specs: { capacityKwh: 15, cells: "LiFePO4" },
    media: [{ file: "IMG-20261002-WA0010.jpg", alt: "Pattern 15kWh LiFePO4 lithium battery on a pallet" }],
  },
  {
    name: "Cworth 16kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 2_300_000,
    specs: { capacityKwh: 16, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0020.jpg", alt: "Cworth Energy 16kWh lithium battery, the maker's promotional picture" }],
  },
  {
    name: "Cworth 3kWh Lithium Battery 24V",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 600_000,
    specs: { capacityKwh: 3, voltage: 24 },
    media: [{ file: "VID-20261002-WA0021.mp4", alt: "Video of the Cworth Energy 3kWh 24V lithium battery, its terminals and its rating label" }],
  },
  {
    name: "Cworth 7.5kWh Lithium Battery 24V",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 1_200_000,
    specs: { capacityKwh: 7.5, voltage: 24, capacityAh: 300 },
    media: [{ file: "VID-20261002-WA0022.mp4", alt: "Video of the Cworth Energy 7.5kWh 24V lithium battery, its terminals and its rating label" }],
  },
  {
    name: "Cworth 20kWh Lithium Battery 48V (Old Design)",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 3_000_000,
    specs: { capacityKwh: 20, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0023.jpg", alt: "Two Cworth Energy LBF-48400C 20kWh lithium batteries side by side" }],
  },
  {
    name: "Cworth 20kWh Lithium Battery 48V (New Design)",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 2_900_000,
    specs: { capacityKwh: 20, voltage: 48 },
    media: [{ file: "VID-20261002-WA0024.mp4", alt: "Video walking round the new-design Cworth Energy 20kWh 48V lithium battery" }],
  },
  {
    name: "Cworth 15kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 1_900_000,
    specs: { capacityKwh: 15, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0055.jpg", alt: "Cworth Energy 15kWh 48V lithium battery on a pallet", crop: [0, 195, 810, 885] }],
  },
  {
    name: "Cworth 12V 100Ah Lithium Battery",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 240_000,
    specs: { capacityAh: 100, voltage: 12 },
    media: [],
    note: "No photo: the one sent with this caption (IMG-20261002-WA0029) shows a 12V 300Ah battery, not the 100Ah.",
  },
  {
    name: "Cworth 12V 200Ah Lithium Battery",
    category: "lithium-batteries",
    brand: "Cworth",
    priceNgn: 360_000,
    specs: { capacityAh: 200, voltage: 12, cells: "LiFePO4" },
    media: [{ file: "IMG-20261002-WA0030.jpg", alt: "Cworth Energy 12V 200Ah LiFePO4 battery on its carton", crop: [0, 100, 676, 980] }],
  },
  {
    name: "Ecolion 5kWh Lithium Battery",
    category: "lithium-batteries",
    brand: "Ecolion",
    priceNgn: 900_000,
    specs: { capacityKwh: 5, cells: "LiFePO4" },
    media: [{ file: "IMG-20261002-WA0034.jpg", alt: "Ecolion 5kWh LiFePO4 battery, front view" }],
    note: "The caption says 48V but the label in the photo reads 25.6V 195Ah, so the voltage is left out.",
  },
  {
    name: "Ecolion 7.68kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Ecolion",
    priceNgn: null,
    specs: { capacityKwh: 7.68, voltage: 48, capacityAh: 150, cells: "LiFePO4" },
    media: [
      { file: "IMG-20260921-WA0067.jpg", alt: "Ecolion 7.68kWh 51.2V 150Ah LiFePO4 battery, front view", crop: [38, 171, 464, 618] },
      { file: "IMG-20261002-WA0049.jpg", alt: "Ecolion 7.68kWh lithium battery in its crate" },
    ],
    note: "No price given.",
  },
  {
    name: "Ecolion 16kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Ecolion",
    priceNgn: null,
    specs: { capacityKwh: 16, voltage: 48, capacityAh: 314, cells: "LiFePO4" },
    media: [{ file: "IMG-20261002-WA0050.jpg", alt: "Ecolion 16kWh 51.2V 314Ah LiFePO4 battery on wheels" }],
    note: "No price given.",
  },
  {
    name: "Deye 16kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Deye",
    priceNgn: 2_700_000,
    specs: { capacityKwh: 16, voltage: 48 },
    media: [{ file: "IMG-20261002-WA0044.jpg", alt: "Deye 16kWh lithium battery on wheels", crop: [0, 316, 540, 539] }],
  },
  {
    name: "Deye 5kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Deye",
    priceNgn: 950_000,
    specs: { capacityKwh: 5, voltage: 48 },
    media: [
      { file: "IMG-20261002-WA0051.jpg", alt: "Deye 5kWh 48V lithium battery" },
      { file: "VID-20261002-WA0088.mp4", alt: "Video of the Deye 5kWh 48V lithium battery being unpacked" },
    ],
    note: "Two prices were sent for this battery on the same day: 1,000,000 with the photo, then 950,000 with the video. The later one is used.",
  },
  {
    name: "Deye 60kWh Lithium Battery (High Voltage)",
    category: "lithium-batteries",
    brand: "Deye",
    priceNgn: 16_500_000,
    specs: { capacityKwh: 60 },
    media: [{ file: "IMG-20261002-WA0048.jpg", alt: "Deye 60kWh high-voltage lithium battery rack" }],
  },
  {
    name: "LVTOPSUN G3 16kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "LVTOPSUN",
    priceNgn: 2_100_000,
    specs: { capacityKwh: 16.07, voltage: 48, capacityAh: 314, cells: "LiFePO4" },
    media: [
      { file: "IMG-20261002-WA0061.jpg", alt: "LVTOPSUN G3 51.2V 314Ah 16.07kWh LiFePO4 power wall", crop: [244, 47, 593, 979] },
      { file: "VID-20260919-WA0053.mp4", alt: "Video of LVTOPSUN G3 (LVTS-512314) battery cartons in our store" },
    ],
    note: 'The "Lvtopsun 15kwh" video of 18 September shows cartons marked LVTS-512314 G3, which is this 16kWh battery, so it is attached here and not listed twice.',
  },
  {
    name: "LVTOPSUN 32kWh Lithium Battery 51.2V",
    category: "lithium-batteries",
    brand: "LVTOPSUN",
    priceNgn: null,
    specs: { capacityKwh: 32, voltage: 51.2, capacityAh: 628, cells: "LiFePO4" },
    media: [{ file: "IMG-20261002-WA0039.jpg", alt: "LVTOPSUN 51.2V 32kWh lithium iron phosphate battery leaflet" }],
    note: "No price given.",
  },
  {
    name: "LVTOPSUN 2.56kWh Lithium Battery 25.6V with Wi-Fi",
    category: "lithium-batteries",
    brand: "LVTOPSUN",
    priceNgn: null,
    specs: { capacityKwh: 2.56, voltage: 25.6, capacityAh: 100, cells: "LiFePO4" },
    media: [{ file: "IMG-20261002-WA0038.jpg", alt: "LVTOPSUN LVTS-256100 25.6V 100Ah 2.56kWh LiFePO4 power wall with Wi-Fi", crop: [249, 57, 492, 633] }],
    note: "No price given.",
  },
  {
    name: "Taico T-Series 20kWh Lithium Battery",
    category: "lithium-batteries",
    brand: "Taico",
    priceNgn: 3_100_000,
    specs: { capacityKwh: 20 },
    media: [{ file: "IMG-20261002-WA0064.jpg", alt: "Taico T-Series 20kWh lithium battery on a pallet" }],
  },
  {
    name: "Taico 5kWh Lithium Battery 24V",
    category: "lithium-batteries",
    brand: "Taico",
    priceNgn: 1_050_000,
    specs: { capacityKwh: 5, voltage: 24 },
    media: [{ file: "IMG-20261002-WA0065.jpg", alt: "Taico 5kWh 24V wall-mounted lithium battery in its carton with cables", crop: [8, 0, 608, 1080] }],
  },
  {
    name: "Taico 10kWh Lithium Battery",
    category: "lithium-batteries",
    brand: "Taico",
    priceNgn: 1_650_000,
    specs: { capacityKwh: 10 },
    media: [{ file: "IMG-20261002-WA0066.jpg", alt: "Taico 10kWh lithium battery, front view" }],
  },

  // ─── Inverter and battery sets (all-in-one units and matched sets) ──────────
  {
    name: "Felicity All-in-One 8kVA Inverter with 10kWh Lithium Battery",
    category: "inverter-and-battery-sets",
    brand: "Felicity",
    priceNgn: 2_500_000,
    specs: { ratedKva: 8, batteryKwh: 10 },
    media: [{ file: "IMG-20260921-WA0100.jpg", alt: "Felicity all-in-one system: 8kVA inverter stacked on a 10kWh lithium battery", crop: [0, 0, 730, 973] }],
  },
  {
    name: "Cworth All-in-One 10kVA Inverter with 16kWh Lithium Battery",
    category: "inverter-and-battery-sets",
    brand: "Cworth",
    priceNgn: 3_000_000,
    specs: { ratedKva: 10, batteryKwh: 16 },
    media: [{ file: "VID-20261002-WA0019.mp4", alt: "Video of the Cworth Energy all-in-one system: 10kVA inverter with a 16kWh lithium battery" }],
  },
  {
    name: "Felicity 30kVA Inverter with 60kWh Lithium Battery",
    category: "inverter-and-battery-sets",
    brand: "Felicity",
    priceNgn: 19_000_000,
    specs: { ratedKva: 30, batteryKwh: 60 },
    media: [{ file: "IMG-20261002-WA0016.jpg", alt: "Felicity 30kVA inverter beside a 60kWh lithium battery rack" }],
  },

  // ─── Solar panels ──────────────────────────────────────────────────────────
  {
    name: "Jinko 780W Bifacial Mono Solar Panel",
    category: "solar-panels",
    brand: "Jinko",
    priceNgn: 160_000,
    specs: { watts: 780, type: "Bifacial monocrystalline" },
    media: [{ file: "IMG-20261002-WA0001.jpg", alt: "Front and back of the Jinko 780W bifacial mono solar panel" }],
  },
  {
    name: "Canadian Solar 650W Mono Solar Panel",
    category: "solar-panels",
    brand: "Canadian Solar",
    priceNgn: 120_000,
    specs: { watts: 650, type: "Monocrystalline" },
    media: [
      { file: "IMG-20261002-WA0004.jpg", alt: "Front of the Canadian Solar 650W mono solar panel", crop: [110, 0, 510, 1080] },
      { file: "IMG-20261002-WA0003.jpg", alt: "Back of the Canadian Solar 650W mono solar panel, with its cables", crop: [100, 0, 540, 1080] },
    ],
  },

  // ─── Solar street lights ───────────────────────────────────────────────────
  {
    name: "Felicity D2 80W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 80, type: ALL_IN_ONE },
    media: [{ file: "VID-20260919-WA0039.mp4", alt: "Video of Felicity D2 80W all-in-one solar street light cartons in our store" }],
    note: "No price given.",
  },
  {
    name: "Felicity P2 60W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: 150_000,
    specs: { watts: 60, type: ALL_IN_ONE },
    media: [{ file: "IMG-20261002-WA0009.jpg", alt: "Two Felicity P2 60W all-in-one solar street lights switched on in their carton" }],
  },
  {
    name: "Wakatek 100W All-in-One Solar Street Light (12 Eyes)",
    category: "solar-street-lights",
    brand: "Wakatek",
    priceNgn: 190_000,
    specs: { watts: 100, type: ALL_IN_ONE },
    media: [{ file: "IMG-20261002-WA0008.jpg", alt: "Wakatek 100W all-in-one solar street light with 12 lamp heads" }],
  },
  {
    name: "Wakatek 60W All-in-One Solar Street Light (8 Eyes)",
    category: "solar-street-lights",
    brand: "Wakatek",
    priceNgn: 170_000,
    specs: { watts: 60, type: ALL_IN_ONE },
    media: [{ file: "IMG-20261002-WA0018.jpg", alt: "Wakatek 60W all-in-one solar street light with 8 lamp heads" }],
  },
  {
    name: "Putian All-in-One Solar Street Light (20 Eyes)",
    category: "solar-street-lights",
    brand: "Putian",
    priceNgn: 280_000,
    specs: { type: ALL_IN_ONE },
    media: [{ file: "IMG-20261002-WA0011.jpg", alt: "Putian all-in-one solar street light with 20 lamp heads" }],
  },
  {
    name: "Putian 100W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Putian",
    priceNgn: 130_000,
    specs: { watts: 100, type: ALL_IN_ONE },
    media: [{ file: "IMG-20261002-WA0012.jpg", alt: "Putian 100W all-in-one solar street light beside its carton" }],
  },
  {
    name: "Putian 300W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Putian",
    priceNgn: 120_000,
    specs: { watts: 300, type: ALL_IN_ONE },
    media: [{ file: "IMG-20261002-WA0013.jpg", alt: "Putian 300W all-in-one solar street light with four LED panels" }],
  },
  {
    name: "All-in-One Solar Street Light (4 Eyes)",
    category: "solar-street-lights",
    brand: null,
    priceNgn: 25_000,
    specs: { type: ALL_IN_ONE },
    media: [{ file: "IMG-20261002-WA0031.jpg", alt: "Carton of the 4-eye all-in-one solar street light", crop: [0, 62, 542, 890] }],
  },

  // ─── Solar freezers ────────────────────────────────────────────────────────
  {
    name: "Bona 200L Solar DC Freezer (BD-200)",
    category: "solar-freezers",
    brand: "Bona",
    priceNgn: 850_000,
    specs: { capacityLitres: 200, power: "DC (solar)" },
    media: [
      { file: "IMG-20261002-WA0002.jpg", alt: "Bona BD-200 solar DC freezer with its door open, beside its carton" },
      { file: "VID-20261002-WA0017.mp4", alt: "Video of the solar freezer running from a battery" },
    ],
  },

  // ─── Accessories ───────────────────────────────────────────────────────────
  {
    name: "DAS Power Smart Solar Security Camera",
    category: "accessories",
    brand: "DAS Power",
    priceNgn: 60_000,
    specs: { type: "Solar security camera" },
    media: [
      { file: "IMG-20260921-WA0040.jpg", alt: "DAS Power smart solar security camera with its carton and fittings" },
      { file: "IMG-20260921-WA0030.jpg", alt: "DAS Power smart solar security camera mounted on a wall" },
    ],
    note: 'The price comes from a caption that only says "60k".',
  },

  // ─── Read off a label only: hidden drafts until the owner names and prices them ─
  {
    name: "Sako 2.56kWh Lithium Battery 25.6V",
    category: "lithium-batteries",
    brand: "Sako",
    priceNgn: null,
    status: "DRAFT",
    specs: { capacityKwh: 2.56, voltage: 25.6, capacityAh: 100 },
    media: [{ file: "IMG-20260921-WA0096.jpg", alt: "Stack of Sako Li-Sun 25.6V 2.56kWh lithium battery cartons" }],
  },
  {
    name: "Ecolion 9kWh Lithium Battery 25.6V",
    category: "lithium-batteries",
    brand: "Ecolion",
    priceNgn: null,
    status: "DRAFT",
    specs: { capacityKwh: 9, voltage: 25.6, capacityAh: 352, cells: "LiFePO4" },
    media: [{ file: "IMG-20260921-WA0058.jpg", alt: "Ecolion 9kWh 25.6V 352Ah LiFePO4 battery in its crate" }],
  },
  {
    name: "Minghong Energy 7.68kWh Power Wall Lithium Battery 25.6V",
    category: "lithium-batteries",
    brand: "Minghong Energy",
    priceNgn: null,
    status: "DRAFT",
    specs: { capacityKwh: 7.68, voltage: 25.6, capacityAh: 300, cells: "LiFePO4" },
    media: [{ file: "IMG-20260921-WA0049.jpg", alt: "Minghong Energy Power Wall 25.6V 300Ah 7.68kWh LiFePO4 battery in its crate" }],
  },
  {
    name: "Hamtem 10kWh Lithium Battery 51.2V",
    category: "lithium-batteries",
    brand: "Hamtem",
    priceNgn: null,
    status: "DRAFT",
    specs: { capacityKwh: 10, voltage: 51.2, cells: "LiFePO4" },
    media: [{ file: "IMG-20260921-WA0062.jpg", alt: "Hamtem 51.2V 10kWh LiFePO4 battery, front view" }],
  },

  // ═══ The catalogue of 3 October 2026 (the makers' pictures) ═══════════════════

  // ─── Felicity solar street lights ──────────────────────────────────────────
  {
    name: "Felicity P3 60W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 60, type: ALL_IN_ONE },
    description: felicityLight(60),
    media: [{ file: "IMG-20261003-WA0026.jpg", alt: "Felicity P3 60W all-in-one solar street light, lamp side and solar panel side" }],
  },
  {
    name: "Felicity P3 80W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 80, type: ALL_IN_ONE },
    description: felicityLight(80),
    media: [{ file: "IMG-20261003-WA0027.jpg", alt: "Felicity P3 80W all-in-one solar street light, lamp side and solar panel side" }],
  },
  {
    name: "Felicity P2 80W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 80, type: ALL_IN_ONE },
    description: felicityLight(80),
    media: [{ file: "IMG-20261003-WA0028.jpg", alt: "Felicity P2 80W all-in-one solar street light with four LED blocks, and its solar panel side" }],
  },
  {
    name: "Felicity P2 40W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 40, type: ALL_IN_ONE },
    description: felicityLight(40),
    media: [{ file: "IMG-20261003-WA0030.jpg", alt: "Felicity P2 40W all-in-one solar street light with two LED blocks, and its solar panel side" }],
  },
  {
    name: "Felicity D2 120W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 120, type: ALL_IN_ONE },
    description: felicityLight(120),
    media: [{ file: "IMG-20261003-WA0031.jpg", alt: "Felicity D2 120W all-in-one solar street light with two rows of LED lenses, and its solar panel side" }],
  },
  {
    name: "Felicity D2 100W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 100, type: ALL_IN_ONE },
    description: felicityLight(100),
    media: [{ file: "IMG-20261003-WA0032.jpg", alt: "Felicity D2 100W all-in-one solar street light with two rows of LED lenses, and its solar panel side" }],
  },
  {
    name: "Felicity D2 60W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 60, type: ALL_IN_ONE },
    description:
      "60W all-in-one solar street light with a monocrystalline panel, a LiFePO4 battery of about 40Ah at 12V and a motion sensor that dims the lamp to save power. 10 to 12 hours at full brightness, charged in 6 to 8 hours of sun. IP65 waterproof. For poles 4 to 6 metres high.",
    media: [{ file: "IMG-20261003-WA0034.jpg", alt: "Felicity D2 60W all-in-one solar street light with two rows of LED lenses, and its solar panel side" }],
  },
  {
    name: "Felicity D2 150W-S All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 150, type: ALL_IN_ONE },
    description:
      "150W all-in-one solar street light with a built-in monocrystalline panel of about 160W, a LiFePO4 battery of about 100Ah at 12V and a motion sensor. 24 to 30 hours of light on a full charge, charged in 6 to 8 hours of sun. IP65 waterproof. For poles 6 to 9 metres high.",
    media: [{ file: "IMG-20261003-WA0035.jpg", alt: "Felicity D2 150W-S all-in-one solar street light with two rows of LED lenses, and its solar panel side" }],
  },
  {
    name: "Felicity FL-A3 100W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 100, type: ALL_IN_ONE },
    description:
      "100W all-in-one solar street light giving about 16,000 lumens, with a 145 to 160W monocrystalline panel, a built-in LiFePO4 battery of about 888Wh and a motion sensor. 24 to 30 hours of light on a full charge, charged in 6 to 8 hours of sun. IP65 waterproof. For poles 6 to 9 metres high.",
    media: [{ file: "IMG-20261003-WA0036.jpg", alt: "Felicity FL-A3 100W all-in-one solar street light with three LED blocks, and its solar panel side" }],
  },
  {
    name: "Felicity A3 60W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 60, type: ALL_IN_ONE },
    description:
      "60W all-in-one solar street light with a monocrystalline panel, a built-in lithium battery and a motion sensor, in a weatherproof aluminium body. No cabling to run, so it suits streets, compounds and places off the grid.",
    media: [{ file: "IMG-20261003-WA0037.jpg", alt: "Felicity A3 60W all-in-one solar street light with two LED blocks, and its solar panel side" }],
    note: "The caption gave no title; the name comes from the description he pasted with it.",
  },
  {
    name: "Felicity A3 30W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 30, type: ALL_IN_ONE },
    description:
      "30W all-in-one solar street light with a monocrystalline panel, a built-in lithium battery and a motion sensor, in a weather-resistant aluminium alloy body. No wiring to run.",
    media: [{ file: "IMG-20261003-WA0038.jpg", alt: "Felicity A3 30W all-in-one solar street light with two LED lamps, and its solar panel side" }],
  },
  {
    name: "Felicity F2 120W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 120, type: ALL_IN_ONE },
    description: felicityLight(120),
    media: [{ file: "IMG-20261003-WA0040.jpg", alt: "Felicity F2 120W all-in-one solar street light mounted on a pole" }],
  },

  // ─── Felicity batteries, panels and charge controllers ─────────────────────
  {
    name: "Felicity FLH-48100UG1 5.12kWh Rack Lithium Battery 48V 100Ah",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: null,
    specs: { capacityKwh: 5.12, voltage: 48, capacityAh: 100, cells: LFP },
    description:
      "48V 100Ah (5.12kWh) LiFePO4 battery module for a 19-inch rack or the Felicity battery cabinet. It has a built-in battery management system, an LCD screen, and RS485, CAN and Wi-Fi links to the inverter. Rated for at least 6,000 cycles at 80% depth of discharge.",
    media: [{ file: "IMG-20261003-WA0039.jpg", alt: "Felicity battery cabinet filled with FLH-48100UG1 rack lithium battery modules" }],
  },
  {
    name: "Felicity Tower 5.12kWh Stackable Lithium Battery",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: null,
    specs: { capacityKwh: 5.12, cells: LFP },
    description:
      "Tower-type LiFePO4 lithium battery of 5.12kWh per module. Modules stack on top of each other to add capacity. Built-in battery management system. Made to work with Felicity inverters.",
    media: [{ file: "IMG-20261003-WA0043.jpg", alt: "Felicity tower-type lithium battery: stacked modules under a unit with a round display" }],
  },
  {
    name: "Felicity LPBF24200-M 5kWh Lithium Battery 24V 200Ah",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: null,
    specs: { capacityKwh: 5, voltage: 24, capacityAh: 200, cells: LFP },
    description: "24V 200Ah LiFePO4 lithium battery with a built-in battery management system. Rated for over 6,000 cycles at 80% depth of discharge.",
    media: [{ file: "IMG-20261003-WA0046.jpg", alt: "Felicity LPBF24200-M 24V 200Ah lithium battery, front view" }],
    note: 'May be the same battery as "Felicity FLA 5kWh Lithium Battery 24V" (₦1,000,000), which is already on the site. The description he pasted with it was for a 48V 100Ah wall-mount battery, so it was not used.',
  },
  {
    name: "Felicity FLA48300 15kWh Lithium Battery 48V 300Ah",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: null,
    specs: { capacityKwh: 15, voltage: 48, capacityAh: 300, cells: LFP },
    description:
      "48V 300Ah LiFePO4 lithium battery on wheels, with a built-in battery management system. Rated for over 6,000 cycles at 80% depth of discharge. More units can be added for more capacity.",
    media: [{ file: "IMG-20261003-WA0047.jpg", alt: "Felicity FLA48300 15kWh lithium battery standing on wheels" }],
    note: "May be the same battery as one of the two Felicity 15kWh batteries already on the site (₦2,000,000 each).",
  },
  {
    name: "Felicity FLA48500 25kWh Lithium Battery 48V 500Ah",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: null,
    specs: { capacityKwh: 25, voltage: 48, capacityAh: 500, cells: LFP },
    description:
      "48V 500Ah LiFePO4 lithium battery on wheels, with a built-in battery management system. Rated for over 6,000 cycles at 80% depth of discharge. Charges fast and loses little charge when standing.",
    media: [{ file: "IMG-20261003-WA0048.jpg", alt: "Felicity FLA48500 25kWh lithium battery standing on wheels" }],
    note: 'May be the same battery as "Felicity 25kWh Lithium Battery" (₦4,000,000), which is already on the site.',
  },
  {
    name: "Felicity LPBF48150 7.2kWh Wall-Mount Lithium Battery 48V 150Ah",
    category: "lithium-batteries",
    brand: "Felicity",
    priceNgn: 1_350_000,
    specs: { capacityKwh: 7.2, voltage: 48, capacityAh: 150, cells: LFP },
    description:
      "48V 150Ah wall-mounted LiFePO4 lithium battery with a built-in battery management system. Rated for over 6,000 cycles at 80% depth of discharge. Works with most hybrid inverters and needs no maintenance.",
    media: [{ file: "IMG-20261003-WA0053.jpg", alt: "Felicity LPBF48150 wall-mount lithium battery, front view" }],
  },
  {
    name: "Felicity G12V200AH 12V 200Ah Gel Battery",
    category: "drycell-batteries",
    brand: "Felicity",
    priceNgn: 294_000,
    specs: { capacityAh: 200, voltage: 12, type: "Gel (sealed VRLA), deep cycle" },
    description:
      "12V 200Ah (C10) deep-cycle gel battery. It is sealed, so it needs no topping up and cannot spill. Made for daily use in solar systems, and for inverters, UPS and telecom equipment.",
    media: [{ file: "IMG-20261003-WA0057.jpg", alt: "Felicity G12V200AH 12V 200Ah gel battery with an orange top" }],
  },
  {
    name: "Felicity 450W Mono Solar Panel",
    category: "solar-panels",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 450, type: "Monocrystalline" },
    description: "450W monocrystalline solar panel with an aluminium frame and tempered glass. It keeps producing in low light, early and late in the day.",
    media: [{ file: "IMG-20261003-WA0041.jpg", alt: "Two Felicity 450W monocrystalline solar panels" }],
  },
  {
    name: "Felicity 550W Mono Solar Panel",
    category: "solar-panels",
    brand: "Felicity",
    priceNgn: null,
    specs: { watts: 550, type: "Monocrystalline half-cell" },
    description:
      "550W monocrystalline half-cell solar panel with an aluminium frame and tempered glass. Half-cells lose less power when part of the panel is shaded. About 2278 × 1134 × 35 mm and 27 to 30 kg.",
    media: [{ file: "IMG-20261003-WA0042.jpg", alt: "Two Felicity 550W monocrystalline half-cell solar panels" }],
  },
  {
    name: "Felicity SCCM 6048 60A MPPT Solar Charge Controller 48V",
    category: "charge-controllers",
    brand: "Felicity",
    priceNgn: null,
    specs: { currentA: 60, systemVoltage: "48V", type: "MPPT" },
    description:
      "60A MPPT solar charge controller for 48V battery systems, with an LCD display. Works with lithium and lead-acid batteries. Protected against overcharge, reversed polarity and short circuit. Mounts on a wall.",
    media: [{ file: "IMG-20261003-WA0045.jpg", alt: "Felicity SCCM 6048 MPPT solar charge controller with its display on" }],
  },
  {
    name: "Felicity SCCM12048-II 120A MPPT Solar Charge Controller",
    category: "charge-controllers",
    brand: "Felicity",
    priceNgn: 250_000,
    specs: { currentA: 120, systemVoltage: "12V, 24V or 48V (detected automatically)", type: "MPPT" },
    description:
      "120A MPPT solar charge controller that detects a 12V, 24V or 48V battery bank by itself. Works with lithium, AGM, gel and flooded batteries. LCD display and MODBUS/SNMP communication.",
    media: [{ file: "IMG-20261003-WA0058.jpg", alt: "Felicity SCCM12048-II 120A MPPT solar charge controller" }],
  },

  // ─── Felicity inverters ────────────────────────────────────────────────────
  {
    name: "Felicity AI100-8048 8kW All-in-One Solar System 48V (Without Batteries)",
    category: "inverters",
    brand: "Felicity",
    priceNgn: null,
    specs: { ratedContinuousW: 8000, systemVoltage: 48, type: "All-in-one, sold without batteries" },
    description:
      "8kW, 48V all-in-one unit: a pure sine wave inverter and an MPPT solar charge controller (up to 8,000W of panels) in one upright cabinet with an LCD display. Takes solar, grid and generator input. Sold here without the battery modules.",
    media: [{ file: "IMG-20261003-WA0049.jpg", alt: "Top of the Felicity AI100-8048 all-in-one solar system, with its round display" }],
  },
  {
    name: "Felicity IVGM 8KLP2G1 8kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Felicity",
    priceNgn: null,
    specs: { ratedKva: 8, systemVoltage: 48, type: HYBRID },
    description:
      "8kVA, 48V hybrid inverter with pure sine wave output and a built-in MPPT solar charge controller. Takes solar, grid and generator input. LCD display; remote monitoring over Wi-Fi or GPRS is optional.",
    media: [{ file: "IMG-20261003-WA0050.jpg", alt: "Felicity IVGM 8KLP2G1 8kVA hybrid inverter, front view" }],
  },
  {
    name: "Felicity IVEM6048 6kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 600_000,
    specs: { ratedKva: 6, systemVoltage: 48, type: HYBRID },
    description:
      "6kVA, 48V hybrid inverter with pure sine wave output and a built-in MPPT solar charge controller (up to 120A). Works with lithium, gel and AGM batteries. Accepts mains from 90 to 280V. LCD display.",
    media: [{ file: "IMG-20261003-WA0051.jpg", alt: "Felicity IVEM6048 6kVA hybrid inverter, front view" }],
    note: 'Close to "Felicity 6kVA Hybrid Inverter 48V (IVEM6048-II)" (₦550,000), which is already on the site. Ask whether they are two models.',
  },
  {
    name: "Felicity IVPS10048 10kVA Pure Sine Wave Inverter 48V",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 900_000,
    specs: { ratedKva: 10, systemVoltage: 48, type: PURE_SINE },
    description: "10kVA, 48V pure sine wave inverter. Works with deep-cycle, AGM and lithium batteries and switches quickly between mains and battery. LCD display.",
    media: [{ file: "IMG-20261003-WA0052.jpg", alt: "Felicity IVPS10048 10kVA pure sine wave inverter, front view" }],
  },
  {
    name: "Felicity IVEM3048-LV 3kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 494_000,
    specs: { ratedKva: 3, systemVoltage: 48, type: HYBRID },
    description:
      "3kVA, 48V hybrid inverter with pure sine wave output and a built-in 60A MPPT solar charge controller. Works with lithium, AGM and gel batteries. Accepts mains from 90 to 280V. LCD display.",
    media: [{ file: "IMG-20261003-WA0054.jpg", alt: "Felicity IVEM3048-LV 3kVA hybrid inverter, front view" }],
  },
  {
    name: "Felicity IVEM8048 8kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 700_000,
    specs: { ratedKva: 8, systemVoltage: 48, type: HYBRID },
    description:
      "8kVA, 48V hybrid inverter with pure sine wave output and a built-in 120A MPPT solar charge controller. Works with lithium, gel and AGM batteries. Accepts mains from 90 to 280V and can charge from mains. LCD display.",
    media: [{ file: "IMG-20261003-WA0055.jpg", alt: "Felicity IVEM8048 8kVA hybrid inverter, front view" }],
  },
  {
    name: "Felicity IVPM7548 7.5kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 600_000,
    specs: { ratedKva: 7.5, systemVoltage: 48, type: HYBRID },
    description:
      "7.5kVA, 48V pure sine wave hybrid inverter with a built-in 120A MPPT solar charge controller that can wake a lithium battery. Accepts mains from 90 to 280V, with grid or battery priority.",
    media: [{ file: "IMG-20261003-WA0056.jpg", alt: "Felicity IVPM7548 7.5kVA hybrid inverter, front view" }],
  },
  {
    name: "Felicity IVGM 50KHP3G01 50kW Three-Phase Hybrid Inverter",
    category: "inverters",
    brand: "Felicity",
    priceNgn: 5_500_000,
    specs: { ratedContinuousW: 50_000, type: "Three-phase hybrid" },
    description:
      "50kW three-phase hybrid inverter for commercial and industrial systems. It joins solar panels, battery storage and the grid, works with lithium and lead-acid batteries, and switches between on-grid and off-grid by itself. Monitored over Wi-Fi.",
    media: [
      { file: "IMG-20261003-WA0059.jpg", alt: "Felicity IVGM 50kW three-phase hybrid inverter, close view of the front" },
      { file: "IMG-20261003-WA0060.jpg", alt: "Felicity IVGM 50kW three-phase hybrid inverter, full front view" },
    ],
  },

  // ─── Yohako inverters ──────────────────────────────────────────────────────
  {
    name: "Yohako 15kVA Pure Sine Wave Inverter 48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 15, systemVoltage: 48, type: PURE_SINE },
    media: [{ file: "IMG-20261003-WA0061.jpg", alt: "Yohako pure sine wave inverter, white with a green stripe" }],
    note: "The caption gave no title; the name is made from his specification (15000VA, 48V) and the Yohako logo in the picture.",
  },
  {
    name: "Yohako 10kVA Pure Sine Wave Inverter",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 10, type: PURE_SINE },
    media: [{ file: "IMG-20261003-WA0062.jpg", alt: "Yohako pure sine wave inverter, upright with a green stripe" }],
  },
  {
    name: "Yohako 7.5kVA Pure Sine Wave Inverter",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { type: PURE_SINE },
    media: [{ file: "IMG-20261003-WA0062.jpg", alt: "Yohako pure sine wave inverter, upright with a green stripe" }],
    note: "The title says 7.5kVA but the specification under it says 8000VA, so the rating is left out of the details.",
  },
  {
    name: "Yohako Zentres 5.5kVA Pure Sine Wave Inverter 24/48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 5.5, type: PURE_SINE },
    media: [{ file: "IMG-20261003-WA0062.jpg", alt: "Yohako pure sine wave inverter, upright with a green stripe" }],
    note: '"Zentres" is kept as he typed it; the picture shows a Yohako inverter. Ask what Zentres means.',
  },
  {
    name: "Yohako Zentres 3.5kVA Pure Sine Wave Inverter 24/48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 3.5, type: PURE_SINE },
    media: [{ file: "IMG-20261003-WA0062.jpg", alt: "Yohako pure sine wave inverter, upright with a green stripe" }],
  },
  {
    name: "Yohako Zentres 2.5kVA Pure Sine Wave Inverter 12/24V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 2.5, type: PURE_SINE },
    description: "Pure sine wave inverter. You choose whether it draws first from mains or from solar.",
    media: [{ file: "IMG-20261003-WA0062.jpg", alt: "Yohako pure sine wave inverter, upright with a green stripe" }],
  },
  {
    name: "Yohako 5kVA High Frequency Hybrid Inverter 48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { systemVoltage: 48, type: "Hybrid, high frequency" },
    description: "48V high-frequency hybrid inverter. Several units can run in parallel, and it accepts solar panel strings of up to 500V DC.",
    media: [{ file: "IMG-20261003-WA0064.jpg", alt: "Yohako high-frequency hybrid solar inverter with parallel function and wide PV voltage" }],
    note: "The title says 5kVA but the line under it says 5.5kVA, so the rating is left out of the details.",
  },
  {
    name: "Yohako 10kVA Yellow Hybrid Inverter 48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 10, ratedContinuousW: 8000, systemVoltage: 48, type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0065.jpg", alt: "Yohako MPPT hybrid inverter with a yellow lower half" }],
  },
  {
    name: "Yohako 5kVA 100A Hybrid Inverter 24/48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0065.jpg", alt: "Yohako MPPT hybrid inverter with a yellow lower half" }],
    note: "The title says 5kVA but the specification says 5500VA and 4400W (the 5.5kVA figures), so the ratings are left out.",
  },
  {
    name: "Yohako 5.5kVA Yellow Hybrid Inverter 24/48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 5.5, ratedContinuousW: 4400, type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0065.jpg", alt: "Yohako MPPT hybrid inverter with a yellow lower half" }],
  },
  {
    name: "Yohako 3.5kVA Yellow Hybrid Inverter 24/48V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 3.5, ratedContinuousW: 3000, type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0065.jpg", alt: "Yohako MPPT hybrid inverter with a yellow lower half" }],
  },
  {
    name: "Yohako 2.5kVA Yellow Hybrid Inverter 12/24V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 2.5, ratedContinuousW: 2000, type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0065.jpg", alt: "Yohako MPPT hybrid inverter with a yellow lower half" }],
  },
  {
    name: "Yohako 1.5kVA Yellow Hybrid Inverter 24V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { systemVoltage: 24, type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0065.jpg", alt: "Yohako MPPT hybrid inverter with a yellow lower half" }],
    note: 'The specification under it is a copy of the 2.5kVA one, so the ratings are left out. May be the same inverter as "Yohako 1.5kVA Pure Sine Wave Inverter 24V" (₦250,000), already on the site.',
  },
  {
    name: "Yohako 10kVA Wall-Mounted Hybrid Inverter 48/96V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 10, ratedContinuousW: 8000, type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0066.jpg", alt: "Yohako wall-mounted hybrid solar inverter, white with a dark centre panel" }],
    note: "The caption gave no title; the name is made from his specification (10000VA, 48/96V, 8000W) and the two wall-mounted inverters that follow it.",
  },
  {
    name: "Yohako 5kVA 100A Hybrid Wall-Mounted Inverter",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0066.jpg", alt: "Yohako wall-mounted hybrid solar inverter, white with a dark centre panel" }],
    note: "The title says 5kVA but the specification says 7500VA, 48/96V and 4400W, so the ratings and voltage are left out.",
  },
  {
    name: "Yohako 5.5kVA Wall-Mounted Inverter 24/48/96V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 5.5, ratedContinuousW: 4400, type: LOW_FREQUENCY_HYBRID },
    description: YOHAKO_HYBRID,
    media: [{ file: "IMG-20261003-WA0066.jpg", alt: "Yohako wall-mounted hybrid solar inverter, white with a dark centre panel" }],
  },
  {
    name: "Yohako 30kVA Inverter 360V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 30, systemVoltage: 360, type: LOW_FREQUENCY },
    description: YOHAKO_TOWER,
    media: [{ file: "IMG-20261003-WA0068.jpg", alt: "Yohako black tower inverter on wheels" }],
    note: "The output was typed as 32kW, which is more than 30kVA can give, so the watts are left out.",
  },
  {
    name: "Yohako 20kVA Inverter 192V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 20, ratedContinuousW: 16_000, systemVoltage: 192, type: LOW_FREQUENCY },
    description: YOHAKO_TOWER,
    media: [{ file: "IMG-20261003-WA0068.jpg", alt: "Yohako black tower inverter on wheels" }],
  },
  {
    name: "Yohako 15kVA IGBT Inverter 96V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 15, ratedContinuousW: 12_000, systemVoltage: 96, type: LOW_FREQUENCY },
    description: YOHAKO_TOWER,
    media: [{ file: "IMG-20261003-WA0068.jpg", alt: "Yohako black tower inverter on wheels" }],
  },
  {
    name: "Yohako 10kVA 96V Tower Inverter",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 10, type: LOW_FREQUENCY },
    description: YOHAKO_TOWER,
    media: [{ file: "IMG-20261003-WA0068.jpg", alt: "Yohako black tower inverter on wheels" }],
    note: "The title says 96V but the specification says 48V and 12kW (more than 10kVA can give), so the voltage and watts are left out.",
  },
  {
    name: "Yohako 10kVA Tower Inverter 48/96/180V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 10, ratedContinuousW: 8000, type: LOW_FREQUENCY },
    description: YOHAKO_TOWER,
    media: [{ file: "IMG-20261003-WA0067.jpg", alt: "Yohako blue tower inverter on wheels" }],
  },
  {
    name: "Yohako 7.5kVA Tower Inverter 48/96/180V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 7.5, ratedContinuousW: 6000, type: LOW_FREQUENCY },
    description: YOHAKO_TOWER,
    media: [{ file: "IMG-20261003-WA0067.jpg", alt: "Yohako blue tower inverter on wheels" }],
  },
  {
    name: "Yohako 5.5kVA Tower Inverter 24/48/96V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 5.5, ratedContinuousW: 4400, type: LOW_FREQUENCY },
    description: YOHAKO_TOWER,
    media: [{ file: "IMG-20261003-WA0067.jpg", alt: "Yohako blue tower inverter on wheels" }],
  },
  {
    name: "Yohako 3.5kVA Tower Inverter 24/48/96V",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 3.5, type: LOW_FREQUENCY },
    description: "Pure sine wave, low-frequency inverter built on a transformer. It can start from the battery with no mains.",
    media: [{ file: "IMG-20261003-WA0067.jpg", alt: "Yohako blue tower inverter on wheels" }],
    note: 'The voltage was typed "3524/48/96" and is read as 24/48/96V; the watts were left blank.',
  },
  {
    name: "Yohako 1kVA Sine Wave Intelligent Power Inverter",
    category: "inverters",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 1, type: "Sine wave" },
    description: "1000VA sine wave inverter. Accepts mains from 175 to 275V and gives 220V.",
    media: [{ file: "IMG-20261003-WA0069.jpg", alt: "Yohako sine wave intelligent power inverter, a low white and blue box" }],
  },

  // ─── Yohako lithium batteries ──────────────────────────────────────────────
  {
    name: "Yohako 15kWh Lithium Battery (Old Model)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 15, cells: LFP },
    description: YOHAKO_OLD_LITHIUM,
    media: [{ file: "IMG-20261003-WA0071.jpg", alt: "Older Yohako lithium battery, a white standing unit with a bulb-shaped display panel" }],
    note: "All four old-model batteries were given the same capacity, 200Ah, so the amp-hours are left out of each.",
  },
  {
    name: "Yohako 10kWh Lithium Battery (Old Model)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 10, cells: LFP },
    description: YOHAKO_OLD_LITHIUM,
    media: [{ file: "IMG-20261003-WA0071.jpg", alt: "Older Yohako lithium battery, a white standing unit with a bulb-shaped display panel" }],
  },
  {
    name: "Yohako 7.5kWh Lithium Battery (Old Model)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 7.5, cells: LFP },
    description: YOHAKO_OLD_LITHIUM,
    media: [{ file: "IMG-20261003-WA0071.jpg", alt: "Older Yohako lithium battery, a white standing unit with a bulb-shaped display panel" }],
  },
  {
    name: "Yohako 5kWh Lithium Battery (Old Model)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 5, cells: LFP },
    description: YOHAKO_OLD_LITHIUM,
    media: [{ file: "IMG-20261003-WA0071.jpg", alt: "Older Yohako lithium battery, a white standing unit with a bulb-shaped display panel" }],
  },
  {
    name: "Yohako 5kWh Stacked Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 4.8, voltage: 48, capacityAh: 100, cells: LFP },
    description:
      "Stackable 48V 100Ah (4.8kWh) LiFePO4 battery with aluminium-shell cells, a battery management system and a metal case. Gives 100A continuously and is rated for 6,000 cycles at 80% depth of discharge. Units connect in parallel for more capacity.",
    media: [{ file: "IMG-20261003-WA0070.jpg", alt: "Yohako stacked-model lithium battery, front view with its display" }],
  },
  {
    name: "Yohako 10kWh Stacked Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 9.6, voltage: 48, capacityAh: 200, cells: LFP },
    description:
      "Stackable 48V 200Ah (9.6kWh) LiFePO4 battery with aluminium-shell cells, a battery management system and a metal case. Gives 200A continuously and is rated for 6,000 cycles at 80% depth of discharge. Units connect in parallel for more capacity.",
    media: [{ file: "IMG-20261003-WA0070.jpg", alt: "Yohako stacked-model lithium battery, front view with its display" }],
  },
  {
    name: "Yohako YHK 15kWh Lithium Battery without Wi-Fi (New Model)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 15.36, voltage: 51.2, capacityAh: 300, cells: LFP },
    description:
      "51.2V 300Ah (15.36kWh) LiFePO4 battery with aluminium-shell cells and a battery management system that guards against overcharge, over-discharge, short circuit and overheating. Charges at up to 200A.",
    media: [{ file: "IMG-20261003-WA0072.jpg", alt: "New-model Yohako YHK lithium battery with carry handles and a bulb-shaped display panel" }],
  },
  {
    name: "Yohako 15kWh 300Ah Wall-Mounted Lithium Battery with Wi-Fi (16S)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 15, capacityAh: 300, cells: LFP },
    description: YOHAKO_WIFI_LITHIUM,
    media: [{ file: "IMG-20261003-WA0073.jpg", alt: "Yohako wall-mounted lithium battery with Wi-Fi, white with a dark centre panel" }],
    note: "The voltage was typed as 25.6V, but 15kWh at 300Ah with 16 cells is a 51.2V battery, so the voltage is left out. The picture is very small (178 × 244).",
  },
  {
    name: "Yohako 23.5kWh 460Ah Standing Lithium Battery with Wi-Fi (16S)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 23.5, voltage: 48, capacityAh: 460, cells: LFP },
    description: YOHAKO_WIFI_LITHIUM,
    media: [{ file: "IMG-20261003-WA0074.jpg", alt: "Yohako standing lithium battery with Wi-Fi, on wheels" }],
  },
  {
    name: "Yohako 17.5kWh 360Ah Standing Lithium Battery with Wi-Fi (16S)",
    category: "lithium-batteries",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityKwh: 17.5, voltage: 48, cells: LFP },
    description: YOHAKO_WIFI_LITHIUM,
    media: [{ file: "IMG-20261003-WA0074.jpg", alt: "Yohako standing lithium battery with Wi-Fi, on wheels" }],
    note: "The title says 360Ah but the specification says 200Ah, so the amp-hours are left out of the details.",
  },

  // ─── Yohako solar pumps ────────────────────────────────────────────────────
  {
    name: "Yohako 1HP Surface Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 1, powerW: 750, type: "Surface (centrifugal)" },
    description: `${YOHAKO_SURFACE_PUMP} 750W. AC 85 to 280V, DC 72 to 350V.`,
    media: [{ file: "IMG-20261003-WA0075.jpg", alt: "Yohako surface solar water pump in an orange carrying frame" }],
  },
  {
    name: "Yohako 1.5HP Surface Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 1.5, powerW: 1100, type: "Surface (centrifugal)" },
    description: `${YOHAKO_SURFACE_PUMP} 1100W. AC 85 to 280V, DC 72 to 350V.`,
    media: [{ file: "IMG-20261003-WA0075.jpg", alt: "Yohako surface solar water pump in an orange carrying frame" }],
  },
  {
    name: "Yohako 2HP Surface Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 2, powerW: 1500, type: "Surface (centrifugal)" },
    description: `${YOHAKO_SURFACE_PUMP} 1500W. AC 85 to 280V, DC 110 to 350V.`,
    media: [{ file: "IMG-20261003-WA0075.jpg", alt: "Yohako surface solar water pump in an orange carrying frame" }],
  },
  {
    name: "Yohako 3HP Surface Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 3, powerW: 2200, type: "Surface (centrifugal)" },
    description: `${YOHAKO_SURFACE_PUMP} 2200W. AC 95 to 280V, DC 200 to 350V.`,
    media: [{ file: "IMG-20261003-WA0075.jpg", alt: "Yohako surface solar water pump in an orange carrying frame" }],
  },
  {
    name: "Yohako 3HP Submersible Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 3, powerW: 2200, maxHeadM: 255, type: "Submersible (borehole)" },
    description: "Brushless submersible solar water pump with a stainless steel impeller and its own controller. 2200W, lifts water up to 255m, 1.25 inch outlet, IP68. Runs on AC 85 to 280V or DC 80 to 430V.",
    media: [{ file: "IMG-20261003-WA0076.jpg", alt: "Yohako stainless steel submersible solar pump beside its controller" }],
    note: "The maximum flow was typed as 6 in the description and 4.0 in the specification, so it is left out.",
  },
  {
    name: "Yohako 2HP Submersible Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 2, powerW: 1500, maxHeadM: 203, type: "Submersible (borehole)" },
    description: "Brushless submersible solar water pump with a stainless steel impeller and its own controller. 1500W, lifts water up to 203m, 1.25 inch outlet, IP68. Runs on AC 85 to 280V or DC 80 to 430V.",
    media: [{ file: "IMG-20261003-WA0076.jpg", alt: "Yohako stainless steel submersible solar pump beside its controller" }],
    note: "The maximum flow was typed as 4.8 in the description and 4.0 in the specification, so it is left out.",
  },
  {
    name: "Yohako 1.5HP Submersible Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 1.5, powerW: 1100, maxHeadM: 101, type: "Submersible (borehole)" },
    description: "Submersible solar water pump (model 4YSC6-101-110-1100-A/D) with its own controller. 1100W, up to 6 cubic metres an hour, lifts water up to 101m, 1.25 inch outlet, IP68. Runs on AC 85 to 280V or DC 80 to 430V.",
    media: [{ file: "IMG-20261003-WA0076.jpg", alt: "Yohako stainless steel submersible solar pump beside its controller" }],
  },
  {
    name: "Yohako 1HP Submersible Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 1, powerW: 750, maxHeadM: 67, type: "Submersible (borehole)" },
    description: "Brushless submersible solar water pump with a stainless steel impeller and its own controller. 750W, up to 6 cubic metres an hour, lifts water up to 67m, 1.25 inch outlet, IP68. Runs on AC 85 to 280V or DC 80 to 430V.",
    media: [{ file: "IMG-20261003-WA0076.jpg", alt: "Yohako stainless steel submersible solar pump beside its controller" }],
  },
  {
    name: "Yohako 0.75HP Submersible Solar Pump",
    category: "solar-pumps",
    brand: "Yohako",
    priceNgn: null,
    specs: { powerHp: 0.75, powerW: 550, maxHeadM: 45, type: "Submersible (borehole)" },
    description: "Brushless submersible solar water pump with a stainless steel impeller and its own controller. 550W, up to 6 cubic metres an hour, lifts water up to 45m, 1.25 inch outlet, IP68. Runs on AC 85 to 280V or DC 80 to 430V.",
    media: [{ file: "IMG-20261003-WA0076.jpg", alt: "Yohako stainless steel submersible solar pump beside its controller" }],
  },

  // ─── Yohako charge controllers ─────────────────────────────────────────────
  {
    name: "Yohako 100A Intelligent MPPT Charge Controller",
    category: "charge-controllers",
    brand: "Yohako",
    priceNgn: null,
    specs: { currentA: 100, type: "MPPT" },
    description: `${YOHAKO_MPPT} Rated 10,400W at 96V, for up to 20,800W of panels.`,
    media: [{ file: "IMG-20261003-WA0078.jpg", alt: "Yohako intelligent MPPT solar charge controller with a yellow lower half" }],
  },
  {
    name: "Yohako 80A Intelligent MPPT Charge Controller",
    category: "charge-controllers",
    brand: "Yohako",
    priceNgn: null,
    specs: { currentA: 80, type: "MPPT" },
    description: `${YOHAKO_MPPT} Rated 8,320W at 96V, for up to 16,640W of panels.`,
    media: [{ file: "IMG-20261003-WA0078.jpg", alt: "Yohako intelligent MPPT solar charge controller with a yellow lower half" }],
  },
  {
    name: "Yohako 60A Intelligent MPPT Charge Controller",
    category: "charge-controllers",
    brand: "Yohako",
    priceNgn: null,
    specs: { currentA: 60, type: "MPPT" },
    description: `${YOHAKO_MPPT} Rated 6,240W at 96V.`,
    media: [{ file: "IMG-20261003-WA0078.jpg", alt: "Yohako intelligent MPPT solar charge controller with a yellow lower half" }],
    note: "The largest panel array was typed as 1248W, less than the controller's own rating (probably 12,480W), so it is left out.",
  },
  {
    name: "Yohako 80A High Voltage Charge Controller 180V",
    category: "charge-controllers",
    brand: "Yohako",
    priceNgn: null,
    specs: { currentA: 80, systemVoltage: "180V to 192V", type: "MPPT, high voltage" },
    description: YOHAKO_MPPT,
    media: [{ file: "IMG-20261003-WA0077.jpg", alt: "Yohako blue MPPT solar charge controller" }],
  },
  {
    name: "Yohako 100A High Voltage Charge Controller 96V",
    category: "charge-controllers",
    brand: "Yohako",
    priceNgn: null,
    specs: { currentA: 100, type: "MPPT, high voltage" },
    description: YOHAKO_MPPT,
    media: [{ file: "IMG-20261003-WA0077.jpg", alt: "Yohako blue MPPT solar charge controller" }],
    note: "The title says 96V but the specification says 180V to 192V, so the battery voltage is left out of the details.",
  },
  {
    name: "Yohako 60A Blue Charge Controller 24-48V",
    category: "charge-controllers",
    brand: "Yohako",
    priceNgn: null,
    specs: { currentA: 60, type: "MPPT" },
    description: YOHAKO_MPPT,
    media: [{ file: "IMG-20261003-WA0077.jpg", alt: "Yohako blue MPPT solar charge controller" }],
    note: "The title says 24-48V but the specification says 96V to 120V, so the battery voltage is left out of the details.",
  },

  // ─── Yohako street lights, freezers, stabilizers, air conditioners, water heaters ─
  {
    name: "Yohako Y4 80W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Yohako",
    priceNgn: null,
    specs: { watts: 80, type: ALL_IN_ONE },
    description: "80W all-in-one solar street light with 120 LEDs (SMD3030) and a 3.2V 60Ah LiFePO4 battery rated for over 2,600 cycles. Works from -20°C to 60°C.",
    media: [{ file: "IMG-20261003-WA0082.jpg", alt: "Y4 80W all-in-one solar street light with four LED strips, and its solar panel side" }],
    note: "The four Y-series street lights were not given a brand; Yohako is taken from the Yohako list they came in.",
  },
  {
    name: "Yohako Y8 80W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Yohako",
    priceNgn: null,
    specs: { watts: 80, type: ALL_IN_ONE },
    description: "80W all-in-one solar street light with a LiFePO4 battery rated for over 2,600 cycles. Works from -20°C to 60°C.",
    media: [{ file: "IMG-20261003-WA0079.jpg", alt: "Y8 80W all-in-one solar street light with eight LED lenses" }],
  },
  {
    name: "Yohako YD 40W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Yohako",
    priceNgn: null,
    specs: { watts: 40, type: ALL_IN_ONE },
    description: "40W all-in-one solar street light with a 3.2V 40Ah LiFePO4 battery and a monocrystalline panel. Lights for more than 48 hours on a full charge.",
    media: [{ file: "IMG-20261003-WA0080.jpg", alt: "YD 40W all-in-one solar street light with three round LED lamps, beside its pole bracket" }],
    note: 'The panel was typed as "6V/150W", which is too large for a 40W light, so it is left out.',
  },
  {
    name: "Yohako Y6 80W All-in-One Solar Street Light",
    category: "solar-street-lights",
    brand: "Yohako",
    priceNgn: null,
    specs: { watts: 80, type: ALL_IN_ONE },
    description: "80W all-in-one solar street light with a 3.2V 80Ah LiFePO4 battery. Charges in 6 hours of sun.",
    media: [{ file: "IMG-20261003-WA0084.jpg", alt: "Y6 80W all-in-one solar street light, solar panel side and lamp side" }],
    note: "The picture is very small (212 × 256).",
  },
  {
    name: "Yohako 318L Freezer",
    category: "solar-freezers",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityLitres: 318, power: FREEZER_POWER },
    description: `318 litre chest freezer drawing 98W. ${YOHAKO_FREEZER}`,
    media: [{ file: "IMG-20261003-WA0086.jpg", alt: "Yohako chest freezer, white with a picture of seafood on the front" }],
  },
  {
    name: "Yohako 218L Freezer",
    category: "solar-freezers",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityLitres: 218, power: FREEZER_POWER },
    description: `218 litre chest deep freezer drawing 68W. ${YOHAKO_FREEZER}`,
    media: [{ file: "IMG-20261003-WA0086.jpg", alt: "Yohako chest freezer, white with a picture of seafood on the front" }],
  },
  {
    name: "Yohako 198L Ice Maker Freezer",
    category: "solar-freezers",
    brand: "Yohako",
    priceNgn: null,
    specs: { power: FREEZER_POWER },
    description: `Upright freezer with drawers, drawing 98W. ${YOHAKO_FREEZER} Uses R134a refrigerant and switches off by itself when the supply voltage is too low.`,
    media: [{ file: "IMG-20261003-WA0088.jpg", alt: "Yohako upright freezer, closed and with its door open showing the drawers" }],
    note: "The title says 198 litres but the specification says 258L (the next freezer's figure), so the capacity is left out of the details.",
  },
  {
    name: "Yohako 258L Ice Cream Freezer",
    category: "solar-freezers",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityLitres: 258, power: FREEZER_POWER },
    description: "258 litre display freezer with sliding glass lids, drawing 98W. Runs straight from a 12V or 24V DC supply such as a solar system, or from mains through an adaptor. Holds -18°C in 55°C heat. Uses R134a refrigerant and switches off by itself when the supply voltage is too low.",
    media: [{ file: "IMG-20261003-WA0081.jpg", alt: "Yohako ice cream display freezer with curved sliding glass lids" }],
  },
  {
    name: "Yohako 250kVA Automatic Voltage Regulator",
    category: "stabilizers",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 250, phase: "Three-phase" },
    description: "Three-phase AC automatic voltage regulator for a 380V supply. Works with an input of 304 to 456V.",
    media: [{ file: "IMG-20261003-WA0085.jpg", alt: "Yohako SBW-250KVA three-phase automatic voltage regulator cabinet" }],
  },
  {
    name: "Yohako 200kVA Automatic Voltage Regulator",
    category: "stabilizers",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 200, phase: "Three-phase" },
    description: "Three-phase AC automatic voltage regulator. Works with an input of 304 to 456V.",
    media: [{ file: "IMG-20261003-WA0087.jpg", alt: "Yohako SBW-200KVA three-phase automatic voltage regulator cabinet" }],
  },
  {
    name: "Yohako 150kVA Automatic Voltage Regulator",
    category: "stabilizers",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 150, phase: "Three-phase" },
    description: "Three-phase AC automatic voltage regulator. Works with an input of 304 to 456V.",
    media: [{ file: "IMG-20261003-WA0083.jpg", alt: "Yohako SBW-150KVA three-phase automatic voltage regulator cabinet" }],
  },
  {
    name: "Yohako 50kVA Automatic Voltage Regulator",
    category: "stabilizers",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 50, phase: "Three-phase" },
    description: "Three-phase AC automatic voltage regulator.",
    media: [{ file: "IMG-20261003-WA0087.jpg", alt: "Yohako SBW three-phase automatic voltage regulator cabinet (the 200kVA model is pictured)" }],
    note: "He sent the 200kVA picture with this one, so the label in the picture reads SBW-200KVA.",
  },
  {
    name: "Yohako SVC-15kVA Stabilizer",
    category: "stabilizers",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 15, phase: "Single-phase" },
    description: "Single-phase AC automatic voltage regulator for homes, computers, test equipment and industry.",
    media: [{ file: "IMG-20261003-WA0089.jpg", alt: "Yohako SVC-15KVA single-phase automatic voltage regulator" }],
  },
  {
    name: "Yohako TNS-30kVA Stabilizer",
    category: "stabilizers",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 30, phase: "Three-phase" },
    description: "Three-phase automatic voltage regulator for homes, computers, test equipment and industry. Works with an input of 170 to 430V.",
    media: [{ file: "IMG-20261003-WA0090.jpg", alt: "Yohako TNS-30KVA three-phase automatic voltage regulator" }],
  },
  {
    name: "Yohako TNS-20kVA Stabilizer",
    category: "stabilizers",
    brand: "Yohako",
    priceNgn: null,
    specs: { ratedKva: 20, phase: "Three-phase" },
    description: "Three-phase automatic voltage regulator for homes, computers, test equipment and industry. Works with an input of 170 to 430V.",
    media: [{ file: "IMG-20261003-WA0091.jpg", alt: "Yohako TNS-20KVA three-phase automatic voltage regulator on wheels" }],
  },
  {
    name: "Yohako 1.5HP AC/DC Solar Air Conditioner",
    category: "inverter-air-conditioners",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityHp: 1.5, type: "AC/DC solar, brushless DC compressor" },
    description: "1.5HP split air conditioner with a brushless DC compressor, drawing 700W. It runs on DC straight from solar, with no inverter needed.",
    media: [{ file: "IMG-20261003-WA0092.jpg", alt: "Yohako AC/DC solar air conditioner: indoor unit above the outdoor unit" }],
  },
  {
    name: "Yohako 1HP AC/DC Solar Air Conditioner",
    category: "inverter-air-conditioners",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityHp: 1, type: "AC/DC solar, brushless DC compressor" },
    description: "1HP split air conditioner with a brushless DC compressor, drawing 500W. It runs on DC straight from solar, with no inverter needed.",
    media: [{ file: "IMG-20261003-WA0092.jpg", alt: "Yohako AC/DC solar air conditioner: indoor unit above the outdoor unit" }],
  },
  {
    name: "Yohako 200L Solar Water Heater",
    category: "solar-water-heaters",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityLitres: 200, type: "Vacuum tube" },
    description: "200 litre solar water heater with vacuum tubes and a strong frame.",
    media: [{ file: "IMG-20261003-WA0093.jpg", alt: "Yohako solar water heater: a tank above a row of vacuum tubes" }],
  },
  {
    name: "Yohako 150L Solar Water Heater",
    category: "solar-water-heaters",
    brand: "Yohako",
    priceNgn: null,
    specs: { capacityLitres: 150, type: "Vacuum tube" },
    description: "150 litre solar water heater with vacuum tubes and a strong frame.",
    media: [{ file: "IMG-20261003-WA0093.jpg", alt: "Yohako solar water heater: a tank above a row of vacuum tubes" }],
  },

  // ─── Sako ──────────────────────────────────────────────────────────────────
  {
    name: "Sako SUNON IV 4.2kVA Hybrid Inverter",
    category: "inverters",
    brand: "Sako",
    priceNgn: 360_000,
    specs: { ratedKva: 4.2, type: HYBRID },
    media: [
      { file: "IMG-20261003-WA0094.jpg", alt: "Sako SUNON IV 4.2kVA hybrid inverter, angled view" },
      { file: "IMG-20261003-WA0107.jpg", alt: "Sako SUNON IV 4.2kVA hybrid inverter, front view" },
    ],
  },
  {
    name: "Sako SUNON IV 6.2kVA Hybrid Inverter",
    category: "inverters",
    brand: "Sako",
    priceNgn: 432_000,
    specs: { ratedKva: 6.2, type: HYBRID },
    media: [{ file: "IMG-20261003-WA0106.jpg", alt: "Sako SUNON IV 6.2kVA hybrid inverter, front view" }],
  },
  {
    name: "Sako SUNON-ECO 10.2kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Sako",
    priceNgn: 828_000,
    specs: { ratedKva: 10.2, systemVoltage: 48, type: HYBRID },
    media: [{ file: "IMG-20261003-WA0105.jpg", alt: "Sako hybrid inverter marked 10200VA" }],
  },
  {
    name: "Sako E-SUN 12kVA Hybrid Inverter",
    category: "inverters",
    brand: "Sako",
    priceNgn: 912_000,
    specs: { ratedKva: 12, type: HYBRID },
    media: [{ file: "IMG-20261003-WA0104.jpg", alt: "Sako E-Sun 12000VA hybrid inverter, front view" }],
  },
  {
    name: "Sako SUNPOLO 14kVA Hybrid Inverter 48V",
    category: "inverters",
    brand: "Sako",
    priceNgn: 1_452_000,
    specs: { ratedKva: 14, systemVoltage: 48, type: HYBRID },
    media: [{ file: "IMG-20261003-WA0103.jpg", alt: "Sako SUNPOLO hybrid inverter with a round display" }],
  },
  {
    name: "Sako E-SUN 3kVA Hybrid Inverter 24V",
    category: "inverters",
    brand: "Sako",
    priceNgn: 294_000,
    specs: { ratedKva: 3, systemVoltage: 24, type: HYBRID },
    media: [{ file: "IMG-20261003-WA0108.jpg", alt: "Sako E-Sun hybrid inverter marked 3000W" }],
  },
  {
    name: "Sako E-SUN 2kVA Hybrid Inverter 12V",
    category: "inverters",
    brand: "Sako",
    priceNgn: 270_000,
    specs: { ratedKva: 2, systemVoltage: 12, type: HYBRID },
    media: [{ file: "IMG-20261003-WA0110.jpg", alt: "Sako E-Sun hybrid inverter marked 2000VA" }],
  },
  {
    name: "Sako E-SUN 1.2kVA Hybrid Inverter",
    category: "inverters",
    brand: "Sako",
    priceNgn: 180_000,
    specs: { ratedKva: 1.2, type: HYBRID },
    media: [{ file: "IMG-20261003-WA0109.jpg", alt: "Sako E-Sun hybrid inverter marked 1200W" }],
  },
  {
    name: "Sako 2.5kWh Lithium Battery 24V (SAKO-2.5KWH-24V)",
    category: "lithium-batteries",
    brand: "Sako",
    priceNgn: 672_000,
    specs: { capacityKwh: 2.5, voltage: 24, cells: LFP },
    media: [{ file: "IMG-20261003-WA0100.jpg", alt: "Sako LiFePO4 lithium battery power bank, front view" }],
    note: 'Probably the same battery as the hidden draft "Sako 2.56kWh Lithium Battery 25.6V", made earlier from a label. If so, delete the draft.',
  },
  {
    name: "Sako 5kWh Lithium Battery",
    category: "lithium-batteries",
    brand: "Sako",
    priceNgn: 1_092_000,
    specs: { capacityKwh: 5, cells: LFP },
    media: [{ file: "IMG-20261003-WA0096.jpg", alt: "Sako 5kWh LiFePO4 lithium battery power bank, front view" }],
  },
  {
    name: "Sako 12.5kWh Lithium Battery 48V",
    category: "lithium-batteries",
    brand: "Sako",
    priceNgn: 1_932_000,
    specs: { capacityKwh: 12.5, voltage: 48, cells: LFP },
    media: [{ file: "IMG-20261003-WA0095.jpg", alt: "Sako 12.5kWh LiFePO4 lithium battery with a round display" }],
  },
  {
    name: "Sako 16kWh Lithium Battery 51.2V",
    category: "lithium-batteries",
    brand: "Sako",
    priceNgn: 2_220_000,
    specs: { capacityKwh: 16, voltage: 51.2, capacityAh: 320 },
    media: [{ file: "IMG-20261003-WA0099.jpg", alt: "Sako 51.2V 320Ah 16kWh lithium battery with Bluetooth and Wi-Fi" }],
    note: "The caption came before its picture. The voltage and amp-hours are read from the label in the picture (51.2V 320Ah 16kWh).",
  },
  {
    name: "Sako Li-Sun 17.5kWh Lithium Battery (SAKO17.5KWH)",
    category: "lithium-batteries",
    brand: "Sako",
    priceNgn: 2_352_000,
    specs: { capacityKwh: 17.5, voltage: 51.2 },
    media: [{ file: "IMG-20261003-WA0102.jpg", alt: "Sako 51.2V 17.5kWh lithium battery on wheels, with carry handles" }],
  },
  {
    name: "Sako Li-Wall Lithium Battery 51.2V",
    category: "lithium-batteries",
    brand: "Sako",
    priceNgn: 4_224_000,
    specs: { voltage: 51.2 },
    media: [{ file: "IMG-20261003-WA0098.jpg", alt: "Sako Li-Wall 51.2V lithium battery power bank on wheels, marked 32kWh" }],
    note: "The caption says 35kWh but the picture he sent with it is marked 32kWh, so the capacity is left out of the name and details. Ask which it is.",
  },
  {
    name: "Sako ESS 300W Solar Generator (Alpha-I-ESS-300W)",
    category: "inverter-and-battery-sets",
    brand: "Sako",
    priceNgn: 282_000,
    specs: { type: "Solar generator, 5 in 1" },
    media: [{ file: "IMG-20261003-WA0101.jpg", alt: "Sako ESS 5-in-1 solar generator: inverter, MPPT, AC charger, 12V DC and USB outputs" }],
  },

  // ─── Africell ──────────────────────────────────────────────────────────────
  {
    name: "Africell 11kVA Hybrid Inverter 48V (AFHB-11K)",
    category: "inverters",
    brand: "Africell",
    priceNgn: 1_050_000,
    specs: { ratedKva: 11, systemVoltage: 48, type: "Hybrid, built-in 12,000W MPPT controller" },
    media: [{ file: "IMG-20261003-WA0111.jpg", alt: "Africell AFHB-11K hybrid inverter in its carton" }],
  },
  {
    name: "Africell HY Wall-Mounted 15.36kWh Lithium Battery 51.2V (LFP-512300)",
    category: "lithium-batteries",
    brand: "Africell",
    priceNgn: null,
    specs: { capacityKwh: 15.36, voltage: 51.2 },
    media: [{ file: "IMG-20261003-WA0112.jpg", alt: "Africell HY wall-mounted LFP-512300 lithium battery, 15.36kWh at 51.2V" }],
    note: 'His caption reads "HY Wall Mounted 512300- (KAGE-WM-512100-HY)". The brand, capacity and voltage are read from the picture; ask what the KAGE code is.',
  },
  {
    name: "Africell HY Wall-Mounted Lithium Battery (512200)",
    category: "lithium-batteries",
    brand: "Africell",
    priceNgn: null,
    media: [{ file: "IMG-20261003-WA0113.jpg", alt: "Africell HY wall-mounted lithium battery on wheels" }],
    note: 'His caption reads "HY Wall Mounted 512200- (KAGE-WM-512100-HY)" and gives no capacity or voltage. The picture is very small (150 × 150).',
  },
];

/** Sent with the catalogue of 3 October 2026 for three products that were already on the site. */
export const CHAT_ADDITIONS: ChatAddition[] = [
  {
    slug: "felicity-p2-60w-all-in-one-solar-street-light",
    description: felicityLight(60),
    media: [{ file: "IMG-20261003-WA0029.jpg", alt: "Felicity P2 60W all-in-one solar street light with three LED blocks, and its solar panel side" }],
  },
  {
    slug: "felicity-d2-80w-all-in-one-solar-street-light",
    description: felicityLight(80),
    media: [{ file: "IMG-20261003-WA0033.jpg", alt: "Felicity D2 80W all-in-one solar street light with two rows of LED lenses, and its solar panel side" }],
  },
  {
    slug: "felicity-hope1000-1kwh-lithium-battery",
    description:
      "Portable 1kWh LiFePO4 power unit with a built-in 250W inverter and MPPT solar charge controller. It charges from solar panels (up to 200W) or from mains and takes over by itself when the power goes off. Weighs about 8.7kg and is rated for up to 8,000 charge cycles.",
    media: [{ file: "IMG-20261003-WA0044.jpg", alt: "Felicity HOPE1000 portable lithium power unit, dark grey" }],
  },
];
